# Generated by Django 3.0.2 on 2020-01-26 01:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200125_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
