# Generated by Django 3.0.2 on 2020-01-26 02:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200125_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=None), null=True, size=None),
        ),
    ]
